version: "3.9"

services: 
  cccat10:
    image: postgres
    container_name: checkout
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=checkout
      - POSTGRES_DB=checkout
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local